# Generated by Django 3.2.6 on 2021-12-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250)),
                ('favIcon', models.ImageField(default='/images/computer-icons-information-png-favpng-g8DtjAPPNhyaU9EdjHQJRnV97_t.jpeg', upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('favorited', models.BooleanField(default=False)),
            ],
        ),
    ]
