# Generated by Django 3.2.6 on 2021-12-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_title_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='favIcon',
            field=models.ImageField(default='/images/computer-icons-information-png-favpng-g8DtjAPPNhyaU9EdjHQJRnV97_t.jpeg', upload_to='images/'),
        ),
    ]
